plugins {
    id 'java-library'
    id 'idea'
    id 'maven-publish'
    id 'net.neoforged.moddev' version '2.0.140'
    id "me.modmuss50.mod-publish-plugin" version "2.0.0-beta.2"
}

tasks.named('wrapper', Wrapper).configure {
    distributionType = Wrapper.DistributionType.BIN
}

apply from: 'https://raw.githubusercontent.com/FTBTeam/mods-meta/v1/gradle/maven.gradle'
apply from: 'https://raw.githubusercontent.com/FTBTeam/mods-meta/v1/gradle/publishing-2.gradle'
apply from: 'https://raw.githubusercontent.com/FTBTeam/mods-meta/v1/gradle/utils.gradle'
apply from: 'https://raw.githubusercontent.com/FTBTeam/mods-meta/v1/gradle/changelog.gradle'

version = createModVersion(project)
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

java.toolchain.languageVersion = JavaLanguageVersion.of(25)

neoForge {
    version = project.neoforge_version

    //accessTransformers = project.files('src/main/resources/META-INF/accesstransformer.cfg')
    runs {
        client {
            client()
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        server {
            server()
            programArgument '--nogui'
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        gameTestServer {
            type = "gameTestServer"
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        data {
            clientData()
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath(), '--existing', file('src/generated/resources/').getAbsolutePath()
        }

        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            logLevel = org.slf4j.event.Level.DEBUG
        }
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

sourceSets.main.resources {
    srcDir 'src/generated/resources'
}

configurations {
    runtimeClasspath.extendsFrom localRuntime
}


repositories {
    mavenLocal()
    maven {
        url = "https://maven.ftb.dev/releases"
        content {
            includeGroup("dev.ftb.mods")
        }
    }
    maven {
        url = "https://maven.ftb.dev/snapshots"
        content {
            includeGroup("dev.ftb.mods")
        }
    }

    maven {
        name = "Illusive Soulworks maven"
        url = "https://maven.theillusivec4.top/"
    }
}

dependencies {
    implementation "dev.ftb.mods:ftb-library-neoforge:${ftb_library_version}"
    implementation "dev.ftb.mods:ftb-teams-neoforge:${ftb_teams_version}"
    implementation "dev.ftb.mods:ftb-chunks-neoforge:${ftb_chunks_version}"

    compileOnly("top.theillusivec4.curios:curios-neoforge:${curios_version}:api")
    localRuntime("top.theillusivec4.curios:curios-neoforge:${curios_version}")
}

tasks.register("sourcesJar", Jar) {
    archiveClassifier.set("sources")
    from sourceSets.main.allJava
}

tasks.named("jar") {
    dependsOn("sourcesJar")
    // Uncomment this if you want to create an API jar
    // dependsOn("apiJar")
}

tasks.withType(ProcessResources).configureEach {
    var replaceProperties = [
            version: version,
            mod_id: mod_id,
            mod_name: readable_name,
            neoforge_version_range: neoforge_version_range,
            neoforge_loader_version: neoforge_loader_version_range,
            minecraft_version_range: minecraft_version_range,
            ftb_library_version_range: ftb_library_version_range,
            ftb_teams_version_range: ftb_teams_version_range,
            ftb_chunks_version_range: ftb_chunks_version_range
    ]

    inputs.properties replaceProperties

    filesMatching(['META-INF/neoforge.mods.toml']) {
        expand replaceProperties
    }

    // Copy in the repos license file
    from(project.rootDir) {
        include 'LICENSE.md'
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8' // Use the UTF-8 charset for Java compilation
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}

createMavenPublishingBlock(project)

publishMods {
    def CFToken = providers.environmentVariable("CURSEFORGE_KEY");

    dryRun = CFToken.getOrNull() == null || providers.environmentVariable("SKIP_CURSEFORGE").getOrNull() != null
    changelog = createChangelog(project)
    version = project.version
    type = createReleaseType(project)

    displayName = "${project.readable_name} ${project.version}"
    modLoaders.add("neoforge")

    changelog = createChangelog(project)
    file = jar.archiveFile
    version = project.version

    curseforge {
        accessToken = CFToken.orElse("missing")
        projectId = project.curseforge_id
        supported_minecraft_versions.split(",").each {
            minecraftVersions.add(it.trim())
        }
        javaVersions.add(JavaVersion.VERSION_25)
        requires('ftb-library-forge')
        optional('jei')
        client = true
        server = true
    }
}
