org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

mod_id=ftbteambases

archives_base_name=ftb-team-bases
maven_group=dev.ftb.mods
readable_name=FTB Team Bases
mod_author=FTB Team

mod_version=1

minecraft_version=26.1.2
supported_minecraft_versions=26.1.2
minecraft_version_range=[26.1.2,27)

neoforge_version=26.1.2.71
neoforge_version_range=[26.1.2.71,27)
neoforge_loader_version_range=[4,)

fabric_loader_version=0.18.6
fabric_api_version=0.149.1+26.1.2
fabric_api_version_range=>=0.149.1+26.1.2

ftb_library_version=26.1.2.6
ftb_library_version_range=[26.1.2.2,27)
ftb_teams_version=26.1.2.4
ftb_teams_version_range=[26.1.2.4,27)
ftb_chunks_version=26.1.2.4
ftb_chunks_version_range=[26.1.2.4,27)

curios_version=15.0.0-beta.2+26.1.2

curseforge_id=1197857
