modLoader = "javafml"
loaderVersion = "[${neoforgeloaderversion},)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mixins]]
config = "ftbteambases-common.mixins.json"

[[mods]]
modId = "ftbteambases"
version = "${version}"
displayName = "FTB Team Bases"
authors = "Me!"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
#logoFile = ""

[[dependencies.ftbteambases]]
modId = "neoforge"
type = "required"
versionRange = "[${neoforgeversion},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ftbteambases]]
modId = "minecraft"
type = "required"
versionRange = "[${mcversion},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ftbteambases]]
modId = "architectury"
type = "required"
versionRange = "[${archversion},)"
ordering = "AFTER"
side = "BOTH"